apiVersion: v1
kind: Secret
metadata:
  name: ai-agent-secrets
type: Opaque
stringData:
  AZURE_OPENAI_ENDPOINT: "https://generix-agent-sweden.services.ai.azure.com"
  AZURE_OPENAI_API_KEY: "TA_CLE_SECRETE_ICI"
  AZURE_OPENAI_API_VERSION: "2024-02-15-preview"
  AZURE_OPENAI_DEPLOYMENT_NAME: "gpt-4o"
